services:

  # Broker MQTT
  broker:
    container_name: mqtt_broker
    build: ./broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./broker/config:/mosquitto/config
    #  - ./broker/data:/mosquitto/data  # <-- Adicionar esta linha para implementar persistência de dados
    #  - ./broker/log:/mosquitto/log    # <-- Opcional, para logs
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "1883"]
      interval: 5s
      start_period: 10s
      timeout: 5s
      retries: 5

# Estoque
  warehouse: 
    build:
      context: .
      dockerfile: entities/warehouse/Dockerfile
    container_name: warehouse
    depends_on:
      broker:
        condition: service_healthy # Verifica se o broker está funcionando antes de iniciar o serviço

# Fornecedor
  supplier:
    build:
      context: .
      dockerfile: entities/supplier/Dockerfile
    container_name: supplier
    depends_on:
      broker:
        condition: service_healthy # Verifica se o broker está funcionando antes de iniciar o serviço

# --- Dashboard ---
  dashboard:
    build:
      context: .
      dockerfile: entities/dashboard/Dockerfile
    container_name: dashboard
    ports:
      - "5000:5000"
    depends_on:
      broker:
        condition: service_healthy
# --- Fábrica 1 ---
  factory1_line_base: &factory1_line_base
    build:
      context: .
      dockerfile: entities/factory1/line/Dockerfile
    depends_on:
      broker:
        condition: service_healthy # Verifica se o broker está funcionando antes de iniciar o serviço

  factory1_line1:
    <<: *factory1_line_base
    container_name: factory1_line1
    environment:
      - LINE_ID=F1-L1
      - PRODUCT_ID=Pv1
      - BATCH_SIZE=60

  factory1_line2:
    <<: *factory1_line_base
    container_name: factory1_line2
    environment:
      - LINE_ID=F1-L2
      - PRODUCT_ID=Pv2
      - BATCH_SIZE=60

  factory1_line3:
    <<: *factory1_line_base
    container_name: factory1_line3
    environment:
      - LINE_ID=F1-L3
      - PRODUCT_ID=Pv3
      - BATCH_SIZE=60

  factory1_line4:
    <<: *factory1_line_base
    container_name: factory1_line4
    environment:
      - LINE_ID=F1-L4
      - PRODUCT_ID=Pv4
      - BATCH_SIZE=60

  factory1_line5:
    <<: *factory1_line_base
    container_name: factory1_line5
    environment:
      - LINE_ID=F1-L5
      - PRODUCT_ID=Pv5
      - BATCH_SIZE=60
