# Usa a imagem oficial do Mosquitto como base
FROM eclipse-mosquitto:latest

# Instala o pacote 'mosquitto-clients', que contém o 'mosquitto_ping'
RUN apk add --no-cache mosquitto-clients netcat-openbsd