# Permite que o broker salve o estado (mensagens, assinaturas) em disco.
# persistence true
# persistence_location /mosquitto/data/

# Envia os logs para a saída padrão, para que possamos vê-los com 'docker-compose logs'.
log_dest stdout

# Abre a porta 1883 para conexões MQTT. Essencial para o funcionamento.
listener 1883
# Permite que clientes se conectem sem usuário/senha. Ideal para desenvolvimento.
allow_anonymous true

# Listener para WebSockets na porta 9001 (conforme seu docker-compose.yml)
listener 9001
protocol websockets
allow_anonymous true